#!/bin/bash

for i in $(seq 1 9); do
    ./hw2 < AllTests/Fixed_tests-${i}_invalid.in >& AllTests/Fixed_tests-${i}_invalid.res
    if diff_output=$(diff AllTests/Fixed_tests-${i}_invalid.res AllTests/Fixed_tests-${i}_invalid.out); then
        echo "Test $i invalid PASSED ✅"
    else
        echo "Test $i invalid FAILED ❌"
        echo "$diff_output"
    fi
    echo ""

    ./hw2 < AllTests/Fixed_tests-${i}_valid.in >& AllTests/Fixed_tests-${i}_valid.res
    if diff_output=$(diff AllTests/Fixed_tests-${i}_valid.res AllTests/Fixed_tests-${i}_valid.out); then
        echo "Test $i valid PASSED ✅"
    else
        echo "Test $i valid FAILED ❌"
        echo "$diff_output"
    fi
    echo ""
done
